// Sample therapist data for First Session
// In production this would come from an API

const therapists = [
  {
    id: "t1",
    name: "Dr. Sarah Chen",
    specialty: ["Anxiety", "Depression", "CBT"],
    ageRange: "13-17",
    insurance: ["Medicaid", "Fidelis"],
    location: "Brooklyn",
    phone: "718-555-0101",
    email: "schen@example.com",
    website: "https://example.com/schen",
    psychologyTodayUrl: "https://psychologytoday.com/us/therapists/schen",
    intakeOrganization: {
      id: "org1",
      name: "Brooklyn Youth Mental Health Collective",
      phone: "718-555-9000",
      therapistsCovered: 12,
    },
  },
  {
    id: "t2",
    name: "Marcus Johnson, LCSW",
    specialty: ["Trauma", "Family Therapy"],
    ageRange: "10-18",
    insurance: ["Medicaid", "Healthfirst"],
    location: "Bronx",
    phone: "718-555-0202",
    email: null,
    website: null,
    psychologyTodayUrl: "https://psychologytoday.com/us/therapists/mjohnson",
    intakeOrganization: null,
  },
  {
    id: "t3",
    name: "Dr. Priya Patel",
    specialty: ["Anxiety", "ADHD", "School Issues"],
    ageRange: "12-18",
    insurance: ["Medicaid", "MetroPlus"],
    location: "Queens",
    phone: "718-555-0303",
    email: "ppatel@example.com",
    website: "https://example.com/ppatel",
    psychologyTodayUrl: null,
    intakeOrganization: {
      id: "org2",
      name: "Queens Adolescent Services Network",
      phone: "718-555-8000",
      therapistsCovered: 8,
    },
  },
  {
    id: "t4",
    name: "Lisa Morales, LMFT",
    specialty: ["Depression", "Family Therapy", "Bilingual (Spanish)"],
    ageRange: "13-19",
    insurance: ["Medicaid", "Affinity"],
    location: "Manhattan",
    phone: "212-555-0404",
    email: "lmorales@example.com",
    website: null,
    psychologyTodayUrl: "https://psychologytoday.com/us/therapists/lmorales",
    intakeOrganization: null,
  },
  {
    id: "t5",
    name: "James Okafor, PsyD",
    specialty: ["Trauma", "Anxiety", "Cultural Identity"],
    ageRange: "14-18",
    insurance: ["Medicaid", "Healthfirst"],
    location: "Brooklyn",
    phone: "718-555-0505",
    email: "jokafor@example.com",
    website: "https://example.com/jokafor",
    psychologyTodayUrl: null,
    intakeOrganization: {
      id: "org1",
      name: "Brooklyn Youth Mental Health Collective",
      phone: "718-555-9000",
      therapistsCovered: 12,
    },
  },
];

export { therapists };
